trigger:
  - main

pool:
  vmImage: ubuntu-latest

container: maven:3.8.1-openjdk-16-slim

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'path'
      jdkDirectory: '/usr/local/openjdk-16'
      publishJUnitResults: false
      mavenAuthenticateFeed: true
      effectivePomSkip: true